### ISSUE TITLE
Pointer dereference may crash the system

### ISSUE THREAD

**Issue by MaJerle** [myDevicesIoT/Cayenne-MQTT-CPP#4]
Hello Cayenne team,

line 212 in file: https://github.com/myDevicesIoT/Cayenne-MQTT-CPP/blob/master/src/CayenneUtils/CayenneUtils.c

There is a bug as while loop should first check if index points to NULL and then to check what is the value on de-reference.

Instead of: `while (*index && index != '\0') {`
It should be: `while (index != NULL && *index) {`

In this case, if `index == NULL`, second part of `if` statement won't get executed and pointer won't be de-referenced => bug free.

This approach may be used on other parts of code aswell, didn't check.

**Comment by jburhenn** [comment]
Nice catch. This has now been fixed in the master branch.
